### ISSUE TITLE
Helper code to add configurable base URL/fetch filters

### ISSUE THREAD

**Issue by stevenyomi** [keiyoushi/extensions-source#1617]
See #1461

- [ ] Add lib and remove BuildConfig version constant usages
- [ ] Add ktlint rule to avoid using BuildConfig version constant (and R class)
- [ ] Update extension namespaces

**Comment by AwkwardPeak7** [comment]
resolved
