### ISSUE TITLE
Migrate to the new multisrc structure

### ISSUE THREAD

**Issue by stevenyomi** [keiyoushi/extensions-source#265]
- [x] Migrate
  - #278
  - #1200
  - #1228
  - #1237
- [x] Rename projects https://github.com/keiyoushi/extensions-source/pull/259#discussion_r1451996277
  - #1240
- [ ] Enforce PR build check on merge (after existing PRs got merged)
- [x] Documentation
- [x] Reuse `baseUrl` in source code (depends on #1617)

## General/long-term todos
- [x] Partial build in CI and PR build checks
- [ ] Scan scripts and audit scripts
- [ ] Custom audit rules enforced with ktlint
- [ ] Rename namespace (depends on #1617)

**Comment by AwkwardPeak7** [comment]
mostly resolved
